pipeline {
    agent any

    environment {
        // Optionally set build number or tag if needed
        IMAGE_TAG = "${env.BUILD_NUMBER ?: 'latest'}"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend-exams') {
                    script {
                        bat "docker build -t backend-exams:${IMAGE_TAG} ."
                    }
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontproj') {
                    script {
                        bat "docker build -t frontproj:${IMAGE_TAG} ."
                    }
                }
            }
        }

        stage('Push to Nexus') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-creds', usernameVariable: 'admin', passwordVariable: 'Admin@2025')]) {
                    script {
                        docker.withRegistry("http://172.20.10.2:8081/repository/docker-releases", "${USERNAME}:${PASSWORD}") {
                            docker.image("backend-exams:${IMAGE_TAG}").push()
                            docker.image("frontproj:${IMAGE_TAG}").push()
                        }
                    }
                }
            }
        }
    }
}
