pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
        NEXUS_URL = 'http://localhost:8081'
        NEXUS_REPO = 'docker-releases'
        NEXUS_CREDENTIALS = credentials('nexus-creds')  // Added credentials() function
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/AhmedBen98/Project_Exams'
            }
        }
        stage('Build Backend') {
            steps {
                dir('backend-exams') {
                    script {
                        dockerImageBackend = docker.build("backend-exams:latest")
                    }
                }
            }
        }
        stage('Build Frontend') {
            steps {
                dir('frontproj') {
                    script {
                        dockerImageFrontend = docker.build("frontproj:latest")
                    }
                }
            }
        }
        stage('Push to Nexus') {
            steps {
                script {
                    docker.withRegistry("${NEXUS_URL}/repository/${NEXUS_REPO}", "${NEXUS_CREDENTIALS}") {
                        dockerImageBackend.push()
                        dockerImageFrontend.push()
                        // Also push with build number if needed
                        dockerImageBackend.push("${env.BUILD_NUMBER}")
                        dockerImageFrontend.push("${env.BUILD_NUMBER}")
                    }
                }
            }
        }
    }
}
