pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
        NEXUS_URL = 'http://localhost:8081'
        NEXUS_REPO = 'docker-releases'
        NEXUS_CREDENTIALS = credentials('nexus-creds')
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/AhmedBen98/Project_Exams'
            }
        }
        stage('Build Backend') {
            steps {
                dir('backend-exams') {
                    script {
                        dockerImage = docker.build("backend-exams:latest")
                    }
                }
            }
        }
        stage('Build Frontend') {
            steps {
                dir('frontproj') {
                    script {
                        dockerImage = docker.build("frontproj:latest")
                    }
                }
            }
        }
        stage('Push to Nexus') {
            steps {
                script {
                    docker.withRegistry("http://127.0.0.1:8081/repository/docker-releases/", NEXUS_CREDENTIALS) {
                        docker.image("backend-exams:latest").push()
                        docker.image("frontproj:latest").push()
                    }
                }
            }
        }
    }
}
